### PR TITLE
updated gravel beta file

### PR DESCRIPTION
**Pull request by dhanek**
few changes as discussed

### CODE REVIEW

**Review by stefankeidel — APPROVED** [review]
LGTM 🤷

**Comment by lefou** [comment]
The travel time and energy costs in gravel_beta profile are much too small.

grafik

**Comment by stefankeidel** [comment]
We already discussed this and decided it doesn't matter much. They're never going to be accurate because we're abusing brouter for something it wasn't made for.

For example, for gravel we're assigning primary roads a higher penalty than a track with `tracktype=grade2`. This would mean energy costs for primary roads is higher than gravel roads, which of course isn't true. 

This is why we decided the route output by the profile is our primary deliverable for now. Maybe we'll go back and multiply all weights by a constant factor to make it a bit more realistic, but it's never going to be accurate for cycling because in most cases you don't want to take the most energy-efficient path :)

**Comment by dhanek** [comment]
Like @stefankeidel explained, the only thing we could do to get more realistic ride times would be to multiply all cost-factors by 5 or so. This would make the total ride time more realistic, but all roads would be shown as "bad route quality" because of the high cost-factor. Still it wouldn't be useful to plan actual ride times because fast roads (paved & concrete) have a higher penalty and would therefore be slower in the calculation than gravel roads, which doesn't make any sense in real life.

**Comment by lefou** [comment]
Makes sense. Thanks for the explanation.

**Comment by stefankeidel** [comment]
Please keep testing and commenting though! All feedback is highly appreciated :)

**Comment by dhanek** [comment]
I double checked again because the cost-factors didn't change that much between profiles to explain the extreme difference in travel time posted by @lefou. Actually there was one line removed `assign validForBikes 1` that increases the travel time again without changing the routing. I will re-add it again, since the travel time gets more realistic. But still take it with a grain of salt because depending on the actual surface of the gravel roads and climbs it still can be very unrealistic.

**Pull request merged**
